name: trade_bot_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6  # BLoC için
  equatable: ^2.0.5     # State ve event karşılaştırmaları için
  #shared_preferences: ^2.3.3  # Verileri yerel olarak saklamak için (örneğin favoriler)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
